#Requires -Version 5.1
# mask installer (Windows) -- run from a clone:  .\install.ps1
# Installs deps and drops a `mask.cmd` launcher on your PATH that runs the CLI
# from this checkout (so `git pull` updates it; no rebuild, no MASK_FRAMEWORK needed).
#
# Override the install dir:  .\install.ps1 -InstallDir C:\some\bin   (or $env:INSTALL_DIR)
param(
  [string]$InstallDir
)

$ErrorActionPreference = 'Stop'

$Repo = $PSScriptRoot
if (-not $InstallDir) {
  if ($env:INSTALL_DIR) { $InstallDir = $env:INSTALL_DIR }
  else { $InstallDir = Join-Path $env:USERPROFILE '.local\bin' }
}
$Bin = Join-Path $InstallDir 'mask.cmd'

if (-not (Get-Command bun -ErrorAction SilentlyContinue)) {
  [Console]::Error.WriteLine('mask: Bun is required but not found. Install it from https://bun.sh then re-run .\install.ps1')
  exit 1
}

Write-Host 'mask: installing dependencies...'
Push-Location $Repo
try {
  bun install --frozen-lockfile | Out-Null
  $installExit = $LASTEXITCODE
} finally {
  Pop-Location
}
if ($installExit -ne 0) { exit $installExit }

New-Item -ItemType Directory -Force $InstallDir | Out-Null
$launcher = @"
@echo off
rem mask launcher -- generated by install.ps1; runs the CLI from the checkout.
bun run "$Repo\src\cli.ts" %*
"@
Set-Content -Path $Bin -Value $launcher -Encoding Ascii
Write-Host "mask: installed launcher -> $Bin"

# PATH check -- never edit the user's PATH; just print the exact line.
$dirs = $env:Path -split ';' | ForEach-Object { $_.TrimEnd('\') }
if ($dirs -contains $InstallDir.TrimEnd('\')) {
  Write-Host ''
  Write-Host 'OK. Try:  mask --version'
} else {
  Write-Host ''
  Write-Host "NOTE: $InstallDir is not on your PATH. Add it for your user account by"
  Write-Host 'running this once in PowerShell, then open a new terminal:'
  Write-Host ''
  Write-Host "    [Environment]::SetEnvironmentVariable('Path', [Environment]::GetEnvironmentVariable('Path','User') + ';$InstallDir', 'User')"
  Write-Host ''
  Write-Host 'Then:  mask --version'
}

Write-Host ''
Write-Host 'Next:  cd your-project; mask init --agent agents-md --out .'
Write-Host '       (Claude Code users: just  mask init)'
