#!/bin/sh
# mask installer — run from a clone: `./install.sh`
# Installs deps and drops a `mask` launcher on your PATH that runs the CLI from
# this checkout (so `git pull` updates it; no rebuild, no MASK_FRAMEWORK needed).
#
# Override the install dir with INSTALL_DIR=/some/bin ./install.sh
set -eu

REPO="$(cd "$(dirname "$0")" && pwd)"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/bin}"
BIN="$INSTALL_DIR/mask"

if ! command -v bun >/dev/null 2>&1; then
  echo "mask: Bun is required but not found. Install it from https://bun.sh then re-run ./install.sh" >&2
  exit 1
fi

echo "mask: installing dependencies…"
( cd "$REPO" && bun install --frozen-lockfile >/dev/null )

mkdir -p "$INSTALL_DIR"
cat > "$BIN" <<EOF
#!/bin/sh
# mask launcher — generated by install.sh; runs the CLI from the checkout.
exec bun run "$REPO/src/cli.ts" "\$@"
EOF
chmod +x "$BIN"
echo "mask: installed launcher -> $BIN"

# PATH check — never edit the user's shell rc; just tell them the exact line.
case ":$PATH:" in
  *":$INSTALL_DIR:"*)
    echo
    echo "✅ Done. Try:  mask --version"
    ;;
  *)
    echo
    echo "⚠ $INSTALL_DIR is not on your PATH. Add this line to your shell rc"
    echo "  (~/.zshrc, ~/.bashrc, …), then open a new terminal:"
    echo
    echo "    export PATH=\"$INSTALL_DIR:\$PATH\""
    echo
    echo "Then:  mask --version"
    ;;
esac

echo
echo "Next:  cd your-project && mask init --agent agents-md --out ."
echo "       (Claude Code users: just  mask init)"
